### ISSUE TITLE
Ondersteun ook Magento zonder inventorymodules

### ISSUE THREAD

**Issue by evs-xsarus** [Itonomy/module-flowbox#5]
Edit: translated to English.

Subject: Support Magento without Inventory modules enabled

It's not possible to use the Flowbox module when the Inventory modules are disabled. After adding a flowboxwidget to a page and saving that page, the following error is shown:

> [2021-03-05 12:51:58] report.CRITICAL: Error: Cannot instantiate interface Magento\InventoryCatalogApi\Model\GetSkusByProductIdsInterface in /home/john/doe/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:121

In code vendor/itonomy/module-flowbox/Block/Widget/Flow.php one can see that the following interface is called:

\Magento\InventoryCatalogApi\Model\GetSkusByProductIdsInterface

Could this call be rewritten so to support Magento without Inventory modules enabled. This because I don't have an option to enable those inventory modules in my Magento installation.

Tnx.

**Comment by RaphaelBronsveld** [comment]
Hi there,

Thanks for the report.
We'll remove the dependency on the inventory modules in the following release.

**Comment by evs-xsarus** [comment]
@RaphaelBronsveld do you have an ETA when this will be released?

**Comment by RaphaelBronsveld** [comment]
Hi @evs-xsarus ,
The issue has been fixed in commit https://github.com/Itonomy/module-flowbox/commit/6c29bd8cb43fc9e1e2b894a28ed00280b57b44ae. If it's high priority, you can use the composer patches package to update the code without having to rely on the version being available in composer.

We're currently waiting for marketplace approval so we can close this issue :)
